export const FETCH_TRENDING_MOVIE_LIST_START =
  "FETCH_TRENDING_MOVIE_LIST_START";
export const FETCH_TRENDING_MOVIE_LIST_SUCCESS =
  "FETCH_TRENDING_MOVIE_LIST_SUCCESS";
export const FETCH_TRENDING_MOVIE_LIST_FAILURE =
  "FETCH_TRENDING_MOVIE_LIST_FAILURE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_EXTRA_RESULTS = "SET_EXTRA_RESULTS";
export const LOAD_MORE_RESULTS_START = "LOAD_MORE_RESULTS_START";
export const LOAD_MORE_RESULTS_SUCCESS = "LOAD_MORE_RESULTS_SUCCESS";
export const LOAD_MORE_RESULTS_FAILURE = "LOAD_MORE_RESULTS_FAILURE";
